# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quality_clip <- function(seq, qual, c, penalty) {
    .Call('_tailquant_quality_clip', PACKAGE = 'tailquant', seq, qual, c, penalty)
}

scan <- function(s, c, n, penalty) {
    .Call('_tailquant_scan', PACKAGE = 'tailquant', s, c, n, penalty)
}

scan_suffix <- function(s, c, suffix, n, penalty, suffix_penalty) {
    .Call('_tailquant_scan_suffix', PACKAGE = 'tailquant', s, c, suffix, n, penalty, suffix_penalty)
}

scan_from <- function(s, c, start, n, penalty) {
    .Call('_tailquant_scan_from', PACKAGE = 'tailquant', s, c, start, n, penalty)
}

